### ISSUE TITLE
Adding new environment variables to speed up nccl collectives in Jax.

### ISSUE THREAD

**Issue by abhinavgoel95** [NVIDIA/JAX-Toolbox#105]
Could we add these environment variables in the JAX containers? They help with some issues we are facing with unexpectedly long nccl kernels.

```
CUDA_DEVICE_MAX_CONNECTIONS=1
NCCL_AVOID_RECORD_STREAMS=1
NCCL_IB_SL=1
NCCL_PROTO=LL128
```
```[tasklist]
### Tasks
```

**Comment by terrykong** [comment]
Two questions:
1. Are these variables model specific, or are they helpful across all models? 
2. Is this pax or t5x specific, or helpful for all?
This will help us narrow down where these should live

**Comment by abhinavgoel95** [comment]
1. Helpful across all models.
2. Should help all frameworks/libraries.

**Comment by yhtang** [comment]
Just out of curiosity, if the variables are helpful across all frameworks, why aren't these set as the default behavior of NCCL?

**Comment by nluehr** [comment]
For the CUDA_DEVICE_MAX_CONNECTIONS=1, it will generally be helpful in JAX/XLA cases because the kernel launches have already been ordered during compilation/scheduling. In the general case, setting MAX_CONNECTIONS=1 can result a ready-to-run kernels getting stuck behind other kernels waiting on execution dependencies.
